model = "gpt-5.4"
model_reasoning_effort = "high"
personality = "pragmatic"
[projects."/home/users/linopeng"]
trust_level = "trusted"

# MCP server setting
[mcp_servers.github]
command = "/home/users/linopeng/.claude/plugins/github-mcp-server/bin/github-mcp-server"
args = ["stdio"]
env = {"GITHUB_PERSONAL_ACCESS_TOKEN" = "YOUR_KEY", "http_proxy" = "http://10.0.1.18:3128", "https_proxy" = "http://10.0.1.18:3128"}

[mcp_servers.andes-bugzilla]
command = "/home/users/linopeng/.nvm/versions/node/v24.12.0/bin/node"
args = ["/home/users/linopeng/.claude/plugins/andes-bugzilla-plugin/scripts/mcp-server.cjs"]
env = {"BUGZILLA_URL" = "http://e-andes.andestech.com/bugzilla5/rest.cgi", "BUGZILLA_API_KEY" = "YOUR_KEY"}

[mcp_servers.andes-gitea]
command = "docker"
args = [
  "run",
  "-i",
  "--rm",
  "-e", "GITEA_ACCESS_TOKEN",
  "-e", "GITEA_HOST",
  "docker.gitea.com/gitea-mcp-server",
  "/app/gitea-mcp",
  "-t", "stdio",
]
env = {"GITEA_HOST" = "https://gitea.andestech.com", "GITEA_ACCESS_TOKEN" = "YOUR_KEY"}

[features]
multi_agent = true
